---

services:
  nginx:
    image: fisher772/nginx-le
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ssl:/etc/nginx/ssl
      - data:/etc/nginx
      - logs:/var/log/nginx
      - le:/var/log/letsencrypt
    environment:
      - TZ=${EKB}
      - LETSENCRYPT=${STATUS}
      - LE_EMAIL=${EMAIL}
      - LE_FQDN=${FQDN}
      - VPN_ADDRESSES=${SEC_IP}
      - VPN_SEC=${SEC_STATUS}
      #- SSL_CERT=le-crt.pem
      #- SSL_KEY=le-key.pem
      #- SSL_CHAIN_CERT=le-chain-crt.pem
      #- LE_ADDITIONAL_OPTIONS='--preferred-chain "ISRG Root X1"'
    networks:
      - nginx

networks:
  nginx:

volumes:
  ssl:
  data:
  logs:
  le:
